/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  agentSidebar: [
    {
      type: 'category',
      label: 'Agent',
      collapsed: false,
      items: [
        'agent/intro',
        {
          type: 'autogenerated',
          dirName: 'agent',
        },
      ],
    },
  ],
  compilerSidebar: [
    {
      type: 'category',
      label: '编译器',
      collapsed: false,
      items: [
        'compiler/intro',
        {
          type: 'autogenerated',
          dirName: 'compiler',
        },
      ],
    },
  ],
  aiinfraSidebar: [
    {
      type: 'category',
      label: 'AI Infra',
      collapsed: false,
      items: [
        'ai-infra/intro',
        {
          type: 'autogenerated',
          dirName: 'ai-infra',
        },
      ],
    },
  ],
};

export default sidebars;
