/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  frontendSidebar: [
    {
      type: 'category',
      label: '前端开发',
      collapsed: false,
      items: [
        'frontend/intro',
        {
          type: 'autogenerated',
          dirName: 'frontend',
        },
      ],
    },
  ],
  backendSidebar: [
    {
      type: 'category',
      label: '后端开发',
      collapsed: false,
      items: [
        'backend/intro',
        {
          type: 'autogenerated',
          dirName: 'backend',
        },
      ],
    },
  ],
  toolsSidebar: [
    {
      type: 'category',
      label: '工具与效率',
      collapsed: false,
      items: [
        'tools/intro',
        {
          type: 'autogenerated',
          dirName: 'tools',
        },
      ],
    },
  ],
};

export default sidebars;
